# Generated by Django 5.0.6 on 2024-06-24 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WAIB3_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entitiesmaster',
            name='url',
            field=models.URLField(default=0),
            preserve_default=False,
        ),
    ]
